import DefaultLayout from "@/layouts/default";

export default function TermsPage() {
    return (
        <DefaultLayout
            title="Terms of Service | HealthTrackerAI"
            description="Learn the rules and conditions for using HealthTrackerAI."
        >
            <main className="min-h-[calc(100vh-8rem)] px-4 py-16 md:px-8 text-slate-100">
                <div className="max-w-3xl mx-auto">
                    <h1 className="text-3xl md:text-4xl font-semibold mb-4">
                        Terms of Service
                    </h1>

                    <p className="text-slate-400 mb-10 text-sm">
                        Last updated: November 2025
                    </p>

                    <section className="space-y-8 text-sm md:text-base leading-relaxed">

                        {/* Intro */}
                        <p>
                            Welcome to <strong>HealthTrackerAI</strong>. These Terms of Service
                            outline the rules and conditions for using our application. By
                            accessing or using HealthTrackerAI, you agree to these terms.
                            This page is intended for academic purposes as part of a senior project.
                        </p>

                        {/* 1. Purpose */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">1. Purpose of the Application</h2>
                            <p className="text-slate-300">
                                HealthTrackerAI is designed to help users track wellness-related
                                data such as calories, workouts, and goals. It is intended for
                                personal use only and does not provide any professional healthcare services.
                            </p>
                        </div>

                        {/* 2. Not Medical Advice */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">2. Not Medical Advice</h2>
                            <p className="text-slate-300">
                                HealthTrackerAI is <strong>not a medical device</strong> and does
                                not provide medical advice, diagnosis, or treatment. All content
                                and recommendations generated by the app or through AI features
                                are for informational purposes only.
                            </p>
                            <p className="text-slate-300 mt-2">
                                Always consult a qualified healthcare provider before making
                                decisions related to your health, exercise routines, diet, or
                                medical conditions.
                            </p>
                        </div>

                        {/* 3. User Responsibilities */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">3. User Responsibilities</h2>
                            <ul className="list-disc pl-6 space-y-2 text-slate-300">
                                <li>You agree to use the app responsibly and respectfully.</li>
                                <li>You will not attempt to hack, disrupt, or misuse the application.</li>
                                <li>You are responsible for maintaining the confidentiality of your login credentials.</li>
                                <li>You agree to provide accurate information when using the app.</li>
                            </ul>
                        </div>

                        {/* 4. AI-Generated Content */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">4. AI-Generated Content</h2>
                            <p className="text-slate-300">
                                Some features of HealthTrackerAI may rely on third-party AI
                                services to generate personalized suggestions or plans. AI
                                outputs may occasionally be inaccurate or incomplete. You agree
                                to use AI-generated content at your own discretion.
                            </p>
                        </div>

                        {/* 5. Limitation of Liability */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">5. Limitation of Liability</h2>
                            <p className="text-slate-300">
                                HealthTrackerAI and its developers are not responsible for any
                                damages, losses, or outcomes resulting from your use of the
                                application, including reliance on AI-generated recommendations,
                                data inaccuracies, downtime, or bugs. The app is provided “as-is”
                                for educational and demonstration purposes.
                            </p>
                        </div>

                        {/* 6. Changes */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">6. Changes to These Terms</h2>
                            <p className="text-slate-300">
                                We may update these Terms of Service occasionally. When changes
                                are made, the updated date at the top of the page will be revised.
                                Continued use of the app means you accept the updated terms.
                            </p>
                        </div>

                        {/* 7. Contact */}
                        <div>
                            <h2 className="text-xl font-semibold mb-2">7. Contact Information</h2>
                            <p className="text-slate-300">
                                For any questions about these Terms of Service, you can contact
                                the project team at:
                                <br />
                                <strong>healthtrackerai-team@example.com</strong>
                            </p>
                        </div>

                        <p className="text-xs text-slate-500 mt-12">
                            This Terms of Service page is created for educational coursework
                            and does not constitute legal advice. A real production
                            application should include terms reviewed by a legal professional.
                        </p>
                    </section>
                </div>
            </main>
        </DefaultLayout>
    );
}